title: Blogging Overload
author: Alexander Huang
email: alxddhuang@gmail.com
description: Alexander Huang's blog, mostly on programming, physics, math, and literature.

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: alexhuangster
    rss: rss

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: alexhuangster/minima
