title: Blogging Overload
author: Alexander Huang
email: alxddhuang@gmail.com
description: Alexander Huang's blog, mostly on programming, physics, math, and literature.

show_excerpts: true

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    github: alexhuangster
    twitter: alxddhuang
    rss: rss

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji

remote_theme: alexhuangster/minima@alex

disqus:
  shortname: alexhuangster

google_analytics:  UA-140787295-1

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Alexander Huang"

markdown: kramdown
kramdown:
  parse_block_html: true
